######################################################################
# Automatically generated by qmake (2.01a) Thu Dec 26 09:38:56 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += epoll.cpp

# Config
CONFIG -= qt
CONFIG += debug
