######################################################################
# Automatically generated by qmake (2.01a) Tue Dec 18 12:45:10 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
