CC = g++
CFLAGS = -g -Wall

all:forloop num_test express forstr1 plus_one bigstep block forstr2 compstr1 \
	while waiting dowhile textin1 textin2 textin3 textin4 nested formore equal \
	compstr2 nestedcl


forloop:forloop.cpp
	$(CC)	$(CFLAGS) $< -o$@

num_test:num_test.cpp
	$(CC)	$(CFLAGS) $< -o$@

express:express.cpp
	$(CC)	$(CFLAGS) $< -o$@

forstr1:forstr1.cpp
	$(CC)	$(CFLAGS) $< -o$@

plus_one:plus_one.cpp
	$(CC)	$(CFLAGS) $< -o$@

bigstep:bigstep.cpp
	$(CC)	$(CFLAGS) $< -o$@


block:block.cpp
	$(CC)	$(CFLAGS) $< -o$@

forstr2:forstr2.cpp
	$(CC)	$(CFLAGS) $< -o$@

compstr1:compstr1.cpp
	$(CC)	$(CFLAGS) $< -o$@

while:while.cpp
	$(CC)	$(CFLAGS) $< -o$@

waiting:waiting.cpp
	$(CC)	$(CFLAGS) $< -o$@

dowhile:dowhile.cpp
	$(CC)	$(CFLAGS) $< -o$@

textin1:textin1.cpp
	$(CC)	$(CFLAGS) $< -o$@

textin2:textin2.cpp
	$(CC)	$(CFLAGS) $< -o$@

textin3:textin3.cpp
	$(CC)	$(CFLAGS) $< -o$@

textin4:textin4.cpp
	$(CC)	$(CFLAGS) $< -o$@

nested:nested.cpp
	$(CC)	$(CFLAGS) $< -o$@

formore:formore.cpp
	$(CC)	$(CFLAGS) $< -o$@

equal:equal.cpp
	$(CC)	$(CFLAGS) $< -o$@

compstr2:compstr2.cpp
	$(CC)	$(CFLAGS) $< -o$@

nestedc1:nestedcl.cpp
	$(CC)	$(CFLAGS) $< -o$@


clean:
	rm -f forloop num_test express forstr1 plus_one bigstep block forstr2 compstr1 \
	while waiting dowhile textin1 textin2 textin3 textin4 nested formore equal \
	compstr2 nestedcl
