CC=g++
CFLAGS= -g -Wall

all:myfirst carrots getinfo sqrt convert ourfunc test

myfirst:myfirst.cpp
	$(CC)	$(CFLAGS) $< -o$@

carrots:carrots.cpp
	$(CC)	$(CFLAGS) $< -o$@

getinfo:getinfo.cpp
	$(CC)	$(CFLAGS) $< -o$@

sqrt:sqrt.cpp
	$(CC)	$(CFLAGS) $< -o$@

convert:convert.cpp
	$(CC)	$(CFLAGS) $< -o$@

ourfunc:ourfunc.cpp
	$(CC)	$(CFLAGS) $< -o$@

test:test.cpp
	$(CC)	$(CFLAGS) $< -o$@


clean:
	rm -f	myfirst carrots getinfo sqrt convert ourfunc test	
