use Mojolicious::Lite;

=comment
Authentication and code shared between multiple routes can be realized easily with bridge routes generated by the "under" statement . All following routes are only evaluated if the callback returned a true value .
=cut

# Authenticate based on name parameter
under sub {
    my $self = shift;

    # Authenticated
    my $name = $self->param('name') || '';
    return 1 if $name eq 'Bender';

    # Not authenticated
    $self->render('denied');
    return undef;
};


# 127.0.0.1:3000
# 127.0.0.1:3000/?name=Bender
# Only reached when authenticated
get '/' => 'index';

app->start;
__DATA__

@@ denied.html.ep
You are not Bender, permission denied.

@@ index.html.ep
Hi Bender.
