######################################################################
# Automatically generated by qmake (2.01a) Tue Dec 18 12:54:24 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += myslots.h
SOURCES += main.cpp myslots.cpp
