CC = g++
CFLAGS = -g -Wall

all:if ifelseif or and more_and not condit switch enum jump \
	cinfish cingolf sumafile cctypes outfile ifelse ifelse2

if:if.cpp
	$(CC) $(CFLAGS) $< -o$@
ifelseif:ifelseif.cpp
	$(CC) $(CFLAGS) $< -o$@
or:or.cpp
	$(CC) $(CFLAGS) $< -o$@
and:and.cpp
	$(CC) $(CFLAGS) $< -o$@
more_and:more_and.cpp
	$(CC) $(CFLAGS) $< -o$@
not:not.cpp
	$(CC) $(CFLAGS) $< -o$@
condit:condit.cpp
	$(CC) $(CFLAGS) $< -o$@
switch:switch.cpp
	$(CC) $(CFLAGS) $< -o$@
enum:enum.cpp
	$(CC) $(CFLAGS) $< -o$@
jump:jump.cpp
	$(CC) $(CFLAGS) $< -o$@
cinfish:cinfish.cpp
	$(CC) $(CFLAGS) $< -o$@
cingolf:cingolf.cpp
	$(CC) $(CFLAGS) $< -o$@
sumafile:sumafile.cpp
	$(CC) $(CFLAGS) $< -o$@
cctypes:cctypes.cpp
	$(CC) $(CFLAGS) $< -o$@
outfile:outfile.cpp
	$(CC) $(CFLAGS) $< -o$@
ifelse:ifelse.cpp
	$(CC) $(CFLAGS) $< -o$@
ifelse2:ifelse2.cpp
	$(CC) $(CFLAGS) $< -o$@

clean:
	rm -f if ifelseif or and more_and not condit switch enum jump \
	cinfish cingolf sumafile cctypes outfile ifelse ifelse2
